<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-06-23T21:04:53 ICT" name="SuiteTest" finished-at="2022-06-23T21:05:28 ICT" duration-ms="35374">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.nexsoft.runner.NewEventRunner@6be968ce]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2022-06-23T21:04:53 ICT" name="Create New Event" finished-at="2022-06-23T21:05:28 ICT" duration-ms="35374">
      <class name="com.nexsoft.runner.NewEventRunner">
        <test-method is-config="true" signature="setUpClass(org.testng.ITestContext)[pri:0, instance:com.nexsoft.runner.NewEventRunner@6be968ce]" started-at="2022-06-23T21:04:53 ICT" name="setUpClass" finished-at="2022-06-23T21:04:53 ICT" duration-ms="714" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@6a98f353]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.nexsoft.runner.NewEventRunner@6be968ce]" started-at="2022-06-23T21:04:53 ICT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2022-06-23T21:05:26 ICT" duration-ms="32388" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Create new event with data"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Create new event"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.nexsoft.definition.NewEventDefine.showUsers(NewEventDefine.java:131)
at âœ½.User showed in Main Activity(file:///D:/Project/Java/TestNG/ContactDiary/src/test/resources/NewEvent.feature:15)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:com.nexsoft.runner.NewEventRunner@6be968ce]" started-at="2022-06-23T21:05:26 ICT" name="tearDownClass" finished-at="2022-06-23T21:05:28 ICT" duration-ms="2207" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- com.nexsoft.runner.NewEventRunner -->
    </test> <!-- Create New Event -->
  </suite> <!-- SuiteTest -->
</testng-results>
