<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="4" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-06-23T00:30:26 ICT" name="Default suite" finished-at="2022-06-23T00:31:15 ICT" duration-ms="48950">
    <groups>
    </groups>
    <test started-at="2022-06-23T00:30:26 ICT" name="Default test" finished-at="2022-06-23T00:31:15 ICT" duration-ms="48950">
      <class name="com.nexsoft.test.CreateEventTest">
        <test-method is-config="true" signature="init()[pri:0, instance:com.nexsoft.test.CreateEventTest@7d9d0818]" started-at="2022-06-23T00:30:26 ICT" name="init" finished-at="2022-06-23T00:30:39 ICT" duration-ms="13267" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="createEvent1()[pri:1, instance:com.nexsoft.test.CreateEventTest@7d9d0818]" started-at="2022-06-23T00:30:39 ICT" name="createEvent1" finished-at="2022-06-23T00:30:56 ICT" duration-ms="16507" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createEvent1 -->
        <test-method signature="createEvent2()[pri:2, instance:com.nexsoft.test.CreateEventTest@7d9d0818]" started-at="2022-06-23T00:30:56 ICT" name="createEvent2" finished-at="2022-06-23T00:31:13 ICT" duration-ms="17482" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createEvent2 -->
        <test-method signature="getEventName()[pri:4, instance:com.nexsoft.test.CreateEventTest@7d9d0818]" started-at="2022-06-23T00:31:13 ICT" name="getEventName" finished-at="2022-06-23T00:31:15 ICT" duration-ms="1605" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Lists differ at element [0]: Ã°Å¸â€œâ€¦   Sparing1 != ðŸ“…   Sparing1 expected [Ã°Å¸â€œâ€¦   Sparing1] but found [ðŸ“…   Sparing1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Lists differ at element [0]: Ã°Å¸â€œâ€¦   Sparing1 != ðŸ“…   Sparing1 expected [Ã°Å¸â€œâ€¦   Sparing1] but found [ðŸ“…   Sparing1]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:1479)
at org.testng.Assert.assertEquals(Assert.java:1441)
at com.nexsoft.test.CreateEventTest.getEventName(CreateEventTest.java:99)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEventName -->
      </class> <!-- com.nexsoft.test.CreateEventTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
